// Comprehensive built-in character knowledge bank
// Richly enriched with canonical lore, companions, settings, rivals, distinctive equipment & landmark milestones

export const CATEGORIES = [
  { id: 'all', name: '🎲 Random Universe', desc: 'Any character from any world' },
  { id: 'anime', name: '⚔️ Anime & Manga', desc: 'Heroes, villains, and legends from iconic series' },
  { id: 'superheroes', name: '🦸 Marvel & DC', desc: 'Superheroes, vigilantes, and cosmic beings' },
  { id: 'gaming', name: '🎮 Gaming Icons', desc: 'Legendary protagonists from video game history' },
  { id: 'movies', name: '🎬 Movies & TV Icons', desc: 'Iconic fictional cinematic personalities' },
  { id: 'tech', name: '💻 Tech Titans & Inventors', desc: 'Innovators who built the digital world' },
  { id: 'science', name: '🔬 Scientists & Great Minds', desc: 'Thinkers who decoded the laws of nature' },
  { id: 'history', name: '👑 Historical Leaders', desc: 'Emperors, generals, and revolutionary icons' },
  { id: 'sports', name: '🏆 Sports Legends', desc: 'GOATs of football, basketball, athletics & more' },
  { id: 'music', name: '🎤 Music Legends', desc: 'Global pop icons and timeless rock stars' }
];

export const CHARACTERS = [
  // ==================== ANIME & MANGA ====================
  {
    name: 'Son Goku',
    aliases: ['goku', 'kakarot', 'songoku'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Planet Vegeta',
    medium: 'anime',
    era: 'modern',
    hair: 'black',
    occupation: 'martial artist',
    alterEgo: true, // Kakarot / Goku
    orphan: false,
    alignment: 'hero',
    weapons: ['martial arts', 'ki blasts', 'power pole', 'spirit bomb'],
    deathType: 'alive',
    conditions: ['alien tail', 'monkey tail'],
    tags: [
      'saiyan', 'dragon ball', 'tail', 'monkey tail', 'super saiyan', 'golden super saiyan',
      'kamehameha', 'flying', 'fighter', 'alien', 'outer space', 'planet vegeta',
      'kakarot', 'martial artist', 'training', 'multiverse', 'chi chi', 'gohan', 'vegeta rival'
    ],
    trivia: 'He was sent to Earth as an infant with the mission to destroy it, but hit his head and became its greatest protector.',
    wikiTitle: 'Goku'
  },
  {
    name: 'Naruto Uzumaki',
    aliases: ['naruto', 'naruto uzumaki', 'seventh hokage'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Hidden Leaf Village',
    medium: 'anime',
    era: 'modern',
    hair: 'blonde',
    occupation: 'ninja',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['kunai', 'shuriken', 'rasengan', 'shadow clones', 'jutsu'],
    deathType: 'alive',
    conditions: ['jinchuriki', 'prosthetic arm'],
    tags: [
      'hokage', 'seventh hokage', 'shinobi', 'nine tails', 'nine-tailed', 'nine-tailed fox', 'kurama',
      'fox spirit', 'ramen', 'ichiraku', 'ichiraku ramen', 'rasengan', 'orange', 'orange jumpsuit',
      'orange tracksuit', 'ninja', 'orphan', 'no parents', 'lonely childhood', 'hidden leaf',
      'hidden leaf village', 'sasuke', 'sakura', 'team 7', 'shadow clone', 'chakra'
    ],
    trivia: 'His signature favorite food is Miso Chashu pork ramen from the Ramen Ichiraku shop.',
    wikiTitle: 'Naruto_Uzumaki'
  },
  {
    name: 'Monkey D. Luffy',
    aliases: ['luffy', 'straw hat luffy', 'monkey d luffy'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'East Blue',
    medium: 'anime',
    era: 'modern',
    hair: 'black',
    occupation: 'pirate',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['rubber punches', 'haki', 'gomu gomu'],
    deathType: 'alive',
    conditions: ['rubber body', 'scar on chest'],
    tags: [
      'one piece', 'straw hat', 'straw hat pirates', 'rubber', 'rubber body', 'gum gum', 'devil fruit',
      'pirate king', 'captain', 'gear fifth', 'sun god nika', 'meat', 'cannot swim', 'swimming',
      'incapable of swimming', 'shanks', 'red-haired shanks', 'grand line', 'east blue', 'zoro', 'sanji'
    ],
    trivia: 'He cannot swim due to eating the Gum-Gum Devil Fruit, ironic for the future King of the Pirates.',
    wikiTitle: 'Monkey_D._Luffy'
  },
  {
    name: 'Levi Ackerman',
    aliases: ['levi', 'captain levi', 'levi ackerman'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Paradis Island',
    medium: 'anime',
    era: 'modern',
    hair: 'black',
    occupation: 'soldier',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['swords', 'blades', 'dual blades', 'odm gear', 'omni-directional mobility', 'thunder spears'],
    deathType: 'alive',
    conditions: ['short stature', 'short height'],
    tags: [
      'attack on titan', 'scout', 'scout regiment', 'survey corps', 'swords', 'blades', 'dual blades',
      'clean freak', 'titan', 'titans', 'titan slayer', 'humanity strongest', 'humanity’s strongest',
      'short', 'short height', 'captain', 'captain levi', 'erwin smith', 'paradis', 'underground city', 'tea'
    ],
    trivia: 'Despite his lethal battlefield prowess, Levi is an obsessive clean freak who drinks tea while holding the cup by its rim.',
    wikiTitle: 'Levi_Ackerman'
  },
  {
    name: 'Light Yagami',
    aliases: ['light', 'kira', 'light yagami'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: true,
    origin: 'Japan',
    medium: 'anime',
    era: 'modern',
    hair: 'brown',
    occupation: 'student',
    alterEgo: true, // Kira
    orphan: false,
    alignment: 'villain',
    weapons: ['death note', 'shinigami notebook', 'pen'],
    deathType: 'assassination', // cardiac arrest via Ryuk
    conditions: [],
    tags: [
      'death note', 'shinigami', 'ryuk', 'notebook', 'death notebook', 'apples', 'genius', 'villain',
      'antagonist', 'criminal', 'murderer', 'detective', 'kira', 'alias kira', 'god of the new world',
      'heart attack', 'cardiac arrest', 'warehouse', 'l rival', 'l lawliet', 'tokyo university',
      'top student', 'academic ranking'
    ],
    trivia: 'He believed he was creating a utopian crime-free world using the supernatural Death Note.',
    wikiTitle: 'Light_Yagami'
  },
  {
    name: 'Saitama',
    aliases: ['saitama', 'one punch man', 'caped baldy'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'City Z',
    medium: 'anime',
    era: 'modern',
    hair: 'bald',
    occupation: 'superhero',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['bare fists', 'serious punch', 'single punch', 'one punch'],
    deathType: 'alive',
    conditions: ['baldness', 'bald'],
    tags: [
      'one punch man', 'bald', 'yellow suit', 'yellow jumpsuit', 'cape', 'white cape', 'red gloves',
      'invincible', 'bored', 'existential boredom', 'hero for fun', 'unpaid hero', 'single punch',
      'defeat any foe', 'grocery sales', 'supermarket', 'genos', '100 pushups'
    ],
    trivia: 'He trained so hard (100 pushups, 100 situps, 100 squats, 10km run daily) that all his hair fell out.',
    wikiTitle: 'Saitama_(One-Punch_Man)'
  },
  {
    name: 'Gojo Satoru',
    aliases: ['gojo', 'satoru gojo', 'gojo satoru'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Japan',
    medium: 'anime',
    era: 'modern',
    hair: 'white',
    occupation: 'teacher',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['cursed energy', 'hollow purple', 'infinity', 'limitless'],
    deathType: 'alive',
    conditions: ['six eyes', 'blindfold'],
    tags: [
      'jujutsu kaisen', 'blindfold', 'infinity', 'limitless', 'six eyes', 'sorcerer', 'special grade',
      'jujutsu high', 'domain expansion', 'infinite void', 'hollow purple', 'white hair', 'teacher'
    ],
    trivia: 'He wears a blindfold because his Six Eyes ability grants him sensory perception so intense it fatigues him.',
    wikiTitle: 'Satoru_Gojo'
  },
  {
    name: 'Edward Elric',
    aliases: ['edward elric', 'ed elric', 'fullmetal alchemist'],
    category: 'anime',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Amestris',
    medium: 'anime',
    era: 'historical',
    hair: 'blonde',
    occupation: 'alchemist',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['alchemy', 'automail arm blade', 'transmutation'],
    deathType: 'alive',
    conditions: ['automail', 'prosthetic limb', 'prosthetic arm', 'prosthetic leg', 'artificial limb', 'amputee'],
    tags: [
      'fullmetal alchemist', 'automail', 'artificial limb', 'prosthetic arm', 'prosthetic leg', 'prosthetic',
      'amputee', 'short', 'short height', 'sensitive about height', 'red coat', 'hooded coat', 'alchemy',
      'alchemist', 'state alchemist', 'silver pocketwatch', 'brother', 'alphonse', 'soul bound to armor',
      'human transmutation', 'philosophers stone', 'amestris'
    ],
    trivia: 'He lost his right arm and left leg during a forbidden human transmutation attempt to resurrect his mother.',
    wikiTitle: 'Edward_Elric'
  },
  {
    name: 'Sailor Moon',
    aliases: ['sailor moon', 'usagi tsukino', 'usagi', 'princess serenity'],
    category: 'anime',
    fictional: true,
    gender: 'female',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Japan',
    medium: 'anime',
    era: 'modern',
    hair: 'blonde',
    occupation: 'magical girl',
    alterEgo: true,
    orphan: false,
    alignment: 'hero',
    weapons: ['magic wand', 'moon stick', 'tiara', 'silver crystal'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'sailor moon', 'magic', 'magical girl', 'tiara', 'luna', 'talking black cat', 'black cat',
      'moon', 'in the name of the moon', 'twin tails', 'meatball buns', 'odango', 'blonde hair',
      'guardian', 'sailor senshi', 'usagi', 'tuxedo mask'
    ],
    trivia: 'Her famous cry "In the name of the Moon, I will punish you!" is one of the most recognized catchphrases in anime.',
    wikiTitle: 'Sailor_Moon_(character)'
  },

  // ==================== MARVEL & DC ====================
  {
    name: 'Iron Man',
    aliases: ['iron man', 'tony stark', 'anthony stark', 'ironman'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'comic',
    era: 'modern',
    hair: 'dark',
    occupation: 'inventor',
    alterEgo: true, // Tony Stark / Iron Man
    orphan: true,
    alignment: 'hero',
    weapons: ['repulsor beams', 'missiles', 'nanotech armor', 'suit'],
    deathType: 'battle',
    conditions: ['arc reactor in chest', 'heart condition'],
    tags: [
      'marvel', 'avengers', 'billionaire', 'wealthy', 'rich', 'armor', 'tech', 'genius', 'arc reactor',
      'flying', 'red and gold', 'stark industries', 'secret identity', 'tony stark', 'cave in afghanistan',
      'endgame sacrifice', 'infinity stones', 'snap', 'pepper potts'
    ],
    trivia: 'He built his original Mark I suit inside a cave in Afghanistan with a box of scraps.',
    wikiTitle: 'Iron_Man'
  },
  {
    name: 'Spider-Man',
    aliases: ['spider-man', 'spiderman', 'peter parker', 'peter'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'USA',
    medium: 'comic',
    era: 'modern',
    hair: 'brown',
    occupation: 'photographer',
    alterEgo: true, // Peter Parker
    orphan: true,
    alignment: 'hero',
    weapons: ['web shooters', 'spider sense'],
    deathType: 'alive',
    conditions: ['spider powers'],
    tags: [
      'marvel', 'avengers', 'web', 'spidey', 'spider', 'wall crawler', 'queens', 'new york city', 'mask',
      'secret identity', 'alter ego', 'peter parker', 'radioactive spider', 'uncle ben', 'great responsibility',
      'daily bugle', 'photographer', 'mary jane', 'aunt may', 'orphan'
    ],
    trivia: 'He was bitten by a radioactive spider on a high school field trip.',
    wikiTitle: 'Spider-Man'
  },
  {
    name: 'Batman',
    aliases: ['batman', 'bruce wayne', 'the dark knight', 'caped crusader'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'comic',
    era: 'modern',
    hair: 'black',
    occupation: 'vigilante',
    alterEgo: true, // Bruce Wayne / Batman
    orphan: true,
    alignment: 'hero',
    weapons: ['batarangs', 'grappling hook', 'smoke bombs', 'batmobile', 'fists'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'dc', 'justice league', 'gotham', 'gotham city', 'batcave', 'billionaire', 'wealthy', 'wayne enterprises',
      'no superpowers', 'lack superpowers', 'without powers', 'secret identity', 'alter ego', 'bruce wayne',
      'detective', 'batmobile', 'orphan', 'parents murdered', 'crime alley', 'alfred', 'no killing', 'never kill'
    ],
    trivia: 'He refuses to use firearms or take a human life, operating purely on peak human conditioning and martial arts.',
    wikiTitle: 'Batman'
  },
  {
    name: 'Superman',
    aliases: ['superman', 'clark kent', 'kal-el', 'man of steel'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Krypton',
    medium: 'comic',
    era: 'modern',
    hair: 'black',
    occupation: 'journalist',
    alterEgo: true, // Clark Kent / Superman
    orphan: true,
    alignment: 'hero',
    weapons: ['heat vision', 'super strength', 'freeze breath'],
    deathType: 'alive',
    conditions: ['alien biology'],
    tags: [
      'dc', 'justice league', 'kryptonite', 'flying', 'laser eyes', 'heat vision', 'freeze breath', 'cape',
      'daily planet', 'alien', 'secret identity', 'alter ego', 'clark kent', 'kal-el', 'krypton', 'orphan',
      'yellow sun', 'smallville', 'jonathan kent', 'martha kent', 'lois lane', 'man of steel'
    ],
    trivia: 'He draws all his godlike powers from the radiation of Earth\'s yellow sun.',
    wikiTitle: 'Superman'
  },
  {
    name: 'Wonder Woman',
    aliases: ['wonder woman', 'diana prince', 'princess diana'],
    category: 'superheroes',
    fictional: true,
    gender: 'female',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Themyscira',
    medium: 'comic',
    era: 'historical',
    hair: 'black',
    occupation: 'warrior',
    alterEgo: true, // Diana Prince
    orphan: false,
    alignment: 'hero',
    weapons: ['lasso of truth', 'shield', 'sword', 'bracelets of submission'],
    deathType: 'alive',
    conditions: ['amazonian goddess'],
    tags: [
      'dc', 'justice league', 'amazon', 'amazonian', 'themyscira', 'lasso of truth', 'golden lasso',
      'shield', 'sword', 'blades', 'bracelets of submission', 'goddess', 'tiara', 'hippolyta',
      'sculpted from clay', 'diana prince'
    ],
    trivia: 'She was sculpted from clay by her mother Hippolyta and blessed with life by Olympian deities.',
    wikiTitle: 'Wonder_Woman'
  },
  {
    name: 'The Joker',
    aliases: ['joker', 'the joker', 'clown prince of crime'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'comic',
    era: 'modern',
    hair: 'green',
    occupation: 'criminal',
    alterEgo: false,
    orphan: false,
    alignment: 'villain',
    weapons: ['joker venom', 'guns', 'crowbar', 'explosives', 'acid flower'],
    deathType: 'alive',
    conditions: ['bleached skin', 'insanity'],
    tags: [
      'dc', 'batman', 'batman arch-nemesis', 'villain', 'antagonist', 'criminal', 'clown', 'laugh',
      'permanent grin', 'gotham', 'makeup', 'purple suit', 'green hair', 'bleached skin', 'insane',
      'theatrical crime', 'chaos', 'no superpowers', 'lack superpowers', 'harley quinn'
    ],
    trivia: 'His true past and origins remain one of the greatest enduring mysteries in comic book lore.',
    wikiTitle: 'Joker_(character)'
  },
  {
    name: 'Thanos',
    aliases: ['thanos', 'the mad titan'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: false,
    human: false,
    superpowers: true,
    origin: 'Titan',
    medium: 'comic',
    era: 'future',
    hair: 'bald',
    occupation: 'warlord',
    alterEgo: false,
    orphan: false,
    alignment: 'villain',
    weapons: ['infinity gauntlet', 'double edged sword', 'cosmic energy'],
    deathType: 'battle',
    conditions: ['deviant syndrome'],
    tags: [
      'marvel', 'avengers', 'infinity stones', 'gauntlet', 'infinity gauntlet', 'snap', 'purple',
      'alien', 'villain', 'antagonist', 'erase half of all life', 'half the universe', 'collect artifacts',
      'titan', 'mad titan', 'black order'
    ],
    trivia: 'He wiped out 50% of all living beings in the universe with a single snap of the Infinity Gauntlet.',
    wikiTitle: 'Thanos'
  },
  {
    name: 'Deadpool',
    aliases: ['deadpool', 'wade wilson', 'merc with a mouth'],
    category: 'superheroes',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Canada',
    medium: 'comic',
    era: 'modern',
    hair: 'bald',
    occupation: 'mercenary',
    alterEgo: true, // Wade Wilson
    orphan: false,
    alignment: 'anti-hero',
    weapons: ['katanas', 'swords', 'guns', 'grenades'],
    deathType: 'alive',
    conditions: ['cancer', 'scarred tissue', 'immortality'],
    tags: [
      'marvel', 'x-men', 'fourth wall', 'break the fourth wall', 'regeneration', 'healing factor',
      'swords', 'katanas', 'guns', 'red suit', 'funny', 'anti-hero', 'mercenary', 'wade wilson'
    ],
    trivia: 'He is aware that he is a fictional comic book character and frequently breaks the fourth wall to speak directly to the audience.',
    wikiTitle: 'Deadpool'
  },

  // ==================== GAMING ICONS ====================
  {
    name: 'Link',
    aliases: ['link', 'hero of time', 'hero of the wild'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Hyrule',
    medium: 'game',
    era: 'historical',
    hair: 'blonde',
    occupation: 'knight',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['master sword', 'hylian shield', 'bow', 'bombs', 'swords'],
    deathType: 'alive',
    conditions: ['silent protagonist', 'pointy ears'],
    tags: [
      'nintendo', 'zelda', 'legend of zelda', 'princess zelda', 'ganon', 'ganondorf', 'master sword',
      'triforce', 'triforce of courage', 'hylian', 'pointed ears', 'green tunic', 'silent', 'silent protagonist',
      'no spoken dialogue', 'no dialogue', 'mute', 'swords', 'blade', 'hyrule'
    ],
    trivia: 'Link is traditionally a silent protagonist so that players could immerse themselves as the avatar of the hero.',
    wikiTitle: 'Link_(The_Legend_of_Zelda)'
  },
  {
    name: 'Mario',
    aliases: ['mario', 'super mario', 'jumpman'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'Mushroom Kingdom',
    medium: 'game',
    era: 'modern',
    hair: 'brown',
    occupation: 'plumber',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['fireball', 'hammer', 'super star'],
    deathType: 'alive',
    conditions: ['mustache'],
    tags: [
      'nintendo', 'nintendo mascot', 'flagship mascot', 'mustache', 'red cap', 'luigi', 'bowser',
      'princess peach', 'peach', 'mushrooms', 'mushroom kingdom', 'fire flower', 'goombas', 'koopa',
      'jump', 'carpenter', 'donkey kong', 'plumber', 'blue overalls'
    ],
    trivia: 'Originally known as "Jumpman" in the 1981 arcade hit Donkey Kong, he was originally a carpenter before becoming a plumber.',
    wikiTitle: 'Mario'
  },
  {
    name: 'Sonic the Hedgehog',
    aliases: ['sonic', 'sonic the hedgehog', 'blue blur'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Mobius',
    medium: 'game',
    era: 'modern',
    hair: 'blue',
    occupation: 'adventurer',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['spin attack', 'homing attack', 'chaos emeralds'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'sega', 'fast', 'supersonic speed', 'rings', 'gold rings', 'chili dogs', 'tails', 'knuckles',
      'dr robotnik', 'eggman', 'dr eggman', 'hedgehog', 'blue hedgehog', 'chaos emeralds', 'super sonic'
    ],
    trivia: 'Sonic cannot swim because programmer Yuji Naka mistakenly believed real hedgehogs could not swim.',
    wikiTitle: 'Sonic_the_Hedgehog'
  },
  {
    name: 'Master Chief',
    aliases: ['master chief', 'john-117', 'chief', 'spartan 117'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Eridanus II',
    medium: 'game',
    era: 'future',
    hair: 'brown',
    occupation: 'soldier',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['assault rifle', 'energy sword', 'plasma grenades'],
    deathType: 'alive',
    conditions: ['augmented cyborg soldier', 'power armor'],
    tags: [
      'halo', 'xbox', 'flagship mascot', 'spartan', 'spartan-117', 'john-117', 'cortana', 'ai cortana',
      'green armor', 'mjolnir', 'golden visor', 'covenant', 'the flood', 'helmet', 'sci-fi', 'space soldier'
    ],
    trivia: 'He is never seen removing his helmet in the mainline video game series.',
    wikiTitle: 'Master_Chief_(Halo)'
  },
  {
    name: 'Kratos',
    aliases: ['kratos', 'ghost of sparta', 'god of war'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Sparta',
    medium: 'game',
    era: 'historical',
    hair: 'bald',
    occupation: 'god',
    alterEgo: false,
    orphan: false,
    alignment: 'anti-hero',
    weapons: ['blades of chaos', 'leviathan axe', 'swords', 'bare hands'],
    deathType: 'alive',
    conditions: ['ash covered skin', 'red tattoo'],
    tags: [
      'playstation', 'god of war', 'blades of chaos', 'atreus', 'bearded', 'red tattoo', 'axe',
      'leviathan axe', 'vengeful quest', 'kill gods', 'mythological deities', 'sparta', 'zeus',
      'ash-white skin', 'greek gods', 'norse realm', 'midgard'
    ],
    trivia: 'His skin is pale ash because he is cursed with the ashes of his slain family bonded permanently to his flesh.',
    wikiTitle: 'Kratos_(God_of_War)'
  },
  {
    name: 'Pikachu',
    aliases: ['pikachu'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Kanto',
    medium: 'game',
    era: 'modern',
    hair: 'yellow',
    occupation: 'pokemon',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['thunderbolt', 'iron tail', 'volt tackle'],
    deathType: 'alive',
    conditions: ['electric cheeks'],
    tags: [
      'pokemon', 'nintendo', 'electric', 'electric mouse', 'ash ketchum', 'pallet town', 'thunderbolt',
      '100000-volt', 'mouse', 'cute', 'tail', 'lightning-bolt tail', 'pika', 'refuses pokeball', 'poké ball'
    ],
    trivia: 'Designed by Atsuko Nishida, Pikachu\'s cheeks were inspired by squirrels storing nuts.',
    wikiTitle: 'Pikachu'
  },
  {
    name: 'Geralt of Rivia',
    aliases: ['geralt', 'geralt of rivia', 'the white wolf', 'butcher of blaviken'],
    category: 'gaming',
    fictional: true,
    gender: 'male',
    alive: true,
    human: false,
    superpowers: true,
    origin: 'Rivia',
    medium: 'game',
    era: 'historical',
    hair: 'white',
    occupation: 'monster hunter',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['silver sword', 'steel sword', 'swords', 'witcher signs'],
    deathType: 'alive',
    conditions: ['mutated through chemical trials', 'cat eyes', 'white hair'],
    tags: [
      'witcher', 'swords', 'blades', 'two swords', 'steel and silver', 'mutant', 'mutated trials',
      'chemical trials', 'trial of the grasses', 'ciri', 'yennefer', 'roach', 'faithful mare roach',
      'alchemy', 'signs', 'white wolf', 'butcher of blaviken', 'the continent'
    ],
    trivia: 'He underwent extensive mutations during the Trial of the Grasses, turning his hair snow-white.',
    wikiTitle: 'Geralt_of_Rivia'
  },

  // ==================== MOVIES & TV ====================
  {
    name: 'Darth Vader',
    aliases: ['darth vader', 'anakin skywalker', 'vader', 'anakin'],
    category: 'movies',
    fictional: true,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: true,
    origin: 'Tatooine',
    medium: 'movie',
    era: 'future',
    hair: 'bald',
    occupation: 'sith lord',
    alterEgo: true, // Anakin Skywalker
    orphan: false,
    alignment: 'villain',
    weapons: ['red lightsaber', 'force choke', 'the force'],
    deathType: 'battle',
    conditions: ['life support armor', 'prosthetic limbs', 'cybernetic suit', 'respirator', 'severe burns'],
    tags: [
      'star wars', 'lightsaber', 'red lightsaber', 'the force', 'black helmet', 'breathing', 'respirator breathing',
      'empire', 'galactic empire', 'emperor palpatine', 'luke father', 'luke skywalker', 'princess leia',
      'life support armor', 'respirator', 'cybernetic', 'prosthetic', 'sith', 'anakin', 'anakin skywalker',
      'mustafar', 'volcanic lava', 'tatooine'
    ],
    trivia: 'His iconic respirator breathing noise was recorded by sound designer Ben Burtt breathing through a scuba regulator.',
    wikiTitle: 'Darth_Vader'
  },
  {
    name: 'Harry Potter',
    aliases: ['harry potter', 'the boy who lived', 'harry'],
    category: 'movies',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: true,
    origin: 'United Kingdom',
    medium: 'movie',
    era: 'modern',
    hair: 'black',
    occupation: 'wizard',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['magic wand', 'spells', 'invisibility cloak'],
    deathType: 'alive',
    conditions: ['lightning bolt scar'],
    tags: [
      'hogwarts', 'wand', 'magic wand', 'glasses', 'lightning scar', 'lightning-bolt scar', 'gryffindor',
      'magic', 'voldemort', 'boarding school', 'magic school', 'orphan', 'parents murdered',
      'lily and james potter', 'ron weasley', 'hermione granger', 'quidditch', 'seeker', 'broomstick'
    ],
    trivia: 'His signature lightning bolt scar was given to him when Voldemort\'s killing curse rebounded.',
    wikiTitle: 'Harry_Potter_(character)'
  },
  {
    name: 'Walter White',
    aliases: ['walter white', 'heisenberg', 'walt'],
    category: 'movies',
    fictional: true,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'movie',
    era: 'modern',
    hair: 'bald',
    occupation: 'chemistry teacher',
    alterEgo: true, // Heisenberg
    orphan: false,
    alignment: 'villain',
    weapons: ['chemistry', 'revolver', 'automated machine gun'],
    deathType: 'cancer/illness',
    conditions: ['lung cancer', 'terminal illness', 'baldness'],
    tags: [
      'breaking bad', 'meth', 'blue sky', 'blue crystal meth', 'albuquerque', 'pork pie hat', 'jesse pinkman',
      'cancer', 'lung cancer', 'terminal illness', 'diagnosed with terminal disease', 'heisenberg',
      'alter ego', 'secret identity', 'chemistry teacher'
    ],
    trivia: 'He used the pseudonym "Heisenberg" as an homage to the theoretical physicist Werner Heisenberg.',
    wikiTitle: 'Walter_White_(Breaking_Bad)'
  },
  {
    name: 'Sherlock Holmes',
    aliases: ['sherlock', 'sherlock holmes', 'holmes'],
    category: 'movies',
    fictional: true,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'United Kingdom',
    medium: 'movie',
    era: 'historical',
    hair: 'dark',
    occupation: 'detective',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['deduction', 'cane', 'fists', 'pistol'],
    deathType: 'natural',
    conditions: [],
    tags: [
      'baker street', '221b baker street', 'watson', 'dr watson', 'medical doctor colleague', 'partner watson',
      'companion watson', 'pipe', 'tobacco pipe', 'violin', 'magnifying glass', 'deduction', 'deductive reasoning',
      'london', 'moriarty', 'professor moriarty', 'consulting detective'
    ],
    trivia: 'He never actually uttered the exact phrase "Elementary, my dear Watson" in any of Arthur Conan Doyle\'s original stories.',
    wikiTitle: 'Sherlock_Holmes'
  },
  {
    name: 'Captain Jack Sparrow',
    aliases: ['jack sparrow', 'captain jack sparrow'],
    category: 'movies',
    fictional: true,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Caribbean',
    medium: 'movie',
    era: 'historical',
    hair: 'brown',
    occupation: 'pirate',
    alterEgo: false,
    orphan: false,
    alignment: 'anti-hero',
    weapons: ['cutlass', 'sword', 'flintlock pistol', 'swords'],
    deathType: 'alive',
    conditions: ['dreadlocks', 'gold teeth'],
    tags: [
      'pirates of the caribbean', 'black pearl', 'compass', 'magical compass', 'dreadlocks', 'rum',
      'caribbean rum', 'johnny depp', 'pirate', 'cutlass', 'flintlock pistol', 'swords'
    ],
    trivia: 'Johnny Depp modeled Jack Sparrow\'s flamboyant walk and demeanor on Rolling Stones guitarist Keith Richards.',
    wikiTitle: 'Jack_Sparrow'
  },

  // ==================== TECH TITANS ====================
  {
    name: 'Steve Jobs',
    aliases: ['steve jobs', 'jobs'],
    category: 'tech',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'bald',
    occupation: 'entrepreneur',
    alterEgo: false,
    orphan: true, // adopted
    alignment: 'hero',
    weapons: ['vision', 'keynotes'],
    deathType: 'cancer/illness',
    conditions: ['pancreatic cancer', 'baldness'],
    tags: [
      'apple', 'iphone', 'mac', 'ipod', 'ipad', 'pixar', 'pixar animation', 'turtleneck', 'black mock turtleneck',
      'silicon valley', 'ousted from company', 'fired from apple', 'adopted', 'pancreatic cancer', 'steve wozniak'
    ],
    trivia: 'He wore his trademark black St. Croix mock turtleneck sweater almost every single day.',
    wikiTitle: 'Steve_Jobs'
  },
  {
    name: 'Elon Musk',
    aliases: ['elon musk', 'elon'],
    category: 'tech',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'South Africa',
    medium: 'real',
    era: 'modern',
    hair: 'brown',
    occupation: 'entrepreneur',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['engineering', 'satellites', 'capital'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'tesla', 'spacex', 'twitter', 'x', 'rebrand to x', 'mars', 'colonize mars', 'rockets',
      'reusable orbital rockets', 'space rockets', 'electric cars', 'neuralink', 'starlink',
      'south africa', 'pretoria', 'paypal', 'x.com'
    ],
    trivia: 'He co-founded Zip2 and X.com (which became PayPal) before launching SpaceX to colonize Mars.',
    wikiTitle: 'Elon_Musk'
  },
  {
    name: 'Bill Gates',
    aliases: ['bill gates', 'gates'],
    category: 'tech',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'grey',
    occupation: 'entrepreneur',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['software', 'philanthropy'],
    deathType: 'alive',
    conditions: ['glasses'],
    tags: [
      'microsoft', 'windows', 'philanthropy', 'philanthropic global health', 'bill and melinda gates foundation',
      'glasses', 'richest', 'richest person in the world', 'software', 'charity', 'harvard dropout',
      'drop out of harvard', 'malaria', 'polio eradication'
    ],
    trivia: 'He wrote his first computer program at age 13 on an ASR-33 Teletype machine.',
    wikiTitle: 'Bill_Gates'
  },
  {
    name: 'Alan Turing',
    aliases: ['alan turing', 'turing'],
    category: 'tech',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'United Kingdom',
    medium: 'real',
    era: 'historical',
    hair: 'brown',
    occupation: 'mathematician',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['mathematics', 'bombe machine'],
    deathType: 'assassination', // cyanide poisoning
    conditions: [],
    tags: [
      'enigma', 'nazi enigma', 'bletchley park', 'computer science', 'father of computer science',
      'father of artificial intelligence', 'turing machine', 'turing test', 'codebreaker', 'ai pioneer',
      'wartime messages', 'intercepting encrypted messages', 'world war ii cipher', 'cyanide poisoning'
    ],
    trivia: 'His machine at Bletchley Park broke the Nazi Enigma cipher, shortening World War II by an estimated two years.',
    wikiTitle: 'Alan_Turing'
  },
  {
    name: 'Mark Zuckerberg',
    aliases: ['mark zuckerberg', 'zuckerberg', 'zuck'],
    category: 'tech',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'brown',
    occupation: 'entrepreneur',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['algorithms', 'social networks'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'facebook', 'meta', 'meta platforms', 'instagram', 'whatsapp', 'harvard dorm', 'social media',
      'metaverse', 'hoodie', 'youngest billionaire'
    ],
    trivia: 'He created Facebook in his Harvard dorm room in 2004 initially for college students.',
    wikiTitle: 'Mark_Zuckerberg'
  },

  // ==================== SCIENTISTS ====================
  {
    name: 'Albert Einstein',
    aliases: ['albert einstein', 'einstein'],
    category: 'science',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'Germany',
    medium: 'real',
    era: 'historical',
    hair: 'white',
    occupation: 'physicist',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['thought experiments', 'theoretical physics'],
    deathType: 'natural',
    conditions: ['mustache'],
    tags: [
      'relativity', 'theory of relativity', 'special relativity', 'general relativity', 'e=mc2',
      'mass-energy equivalence', 'nobel prize', '1921 nobel prize', 'photoelectric effect', 'mustache',
      'unruly white hair', 'physics', 'genius', 'quantum', 'flee europe', 'fled nazi germany',
      'persecution before world war ii', 'princeton', 'princeton university'
    ],
    trivia: 'He won the 1921 Nobel Prize in Physics not for Relativity, but for his discovery of the law of the photoelectric effect.',
    wikiTitle: 'Albert_Einstein'
  },
  {
    name: 'Isaac Newton',
    aliases: ['isaac newton', 'sir isaac newton', 'newton'],
    category: 'science',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'United Kingdom',
    medium: 'real',
    era: 'historical',
    hair: 'grey',
    occupation: 'physicist',
    alterEgo: false,
    orphan: true,
    alignment: 'hero',
    weapons: ['calculus', 'optics'],
    deathType: 'natural',
    conditions: [],
    tags: [
      'gravity', 'law of gravitation', 'apple', 'calculus', 'invent calculus', 'laws of motion',
      'three laws of motion', 'optics', 'spectrum of colors', 'white light prism', 'principia',
      'principia mathematica', 'cambridge', 'quarantined during plague', 'great plague of london', 'royal mint'
    ],
    trivia: 'During the Great Plague of 1665, while quarantined at home, he formulated calculus and the law of universal gravitation.',
    wikiTitle: 'Isaac_Newton'
  },
  {
    name: 'Marie Curie',
    aliases: ['marie curie', 'madame curie'],
    category: 'science',
    fictional: false,
    gender: 'female',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'Poland',
    medium: 'real',
    era: 'historical',
    hair: 'grey',
    occupation: 'chemist',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['chemistry'],
    deathType: 'cancer/illness',
    conditions: ['radiation exposure'],
    tags: [
      'radiation', 'radium', 'polonium', 'radioactive isotopes', 'radioactivity', 'nobel prize',
      'two nobel prizes', 'two distinct sciences', 'physics and chemistry', 'warsaw poland', 'paris',
      'sorbonne', 'first female professor', 'aplastic anemia'
    ],
    trivia: 'She remains the only person to ever win Nobel Prizes in two distinct scientific fields (Physics and Chemistry).',
    wikiTitle: 'Marie_Curie'
  },
  {
    name: 'Nikola Tesla',
    aliases: ['nikola tesla', 'tesla'],
    category: 'science',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'Croatia',
    medium: 'real',
    era: 'historical',
    hair: 'black',
    occupation: 'inventor',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['electricity', 'coils'],
    deathType: 'natural',
    conditions: ['mustache'],
    tags: [
      'electricity', 'ac power', 'alternating current', 'tesla coil', 'wireless', 'mustache',
      'edison rival', 'war of the currents', 'serbian heritage', 'pigeon', 'urban pigeons'
    ],
    trivia: 'He had a photographic memory and could visualize entire complex mechanical inventions in his head before building them.',
    wikiTitle: 'Nikola_Tesla'
  },

  // ==================== HISTORICAL LEADERS ====================
  {
    name: 'Julius Caesar',
    aliases: ['julius caesar', 'caesar'],
    category: 'history',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'Rome',
    medium: 'real',
    era: 'historical',
    hair: 'bald',
    occupation: 'emperor',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['gladius', 'legions'],
    deathType: 'assassination',
    conditions: ['stab wounds'],
    tags: [
      'roman empire', 'ides of march', 'rubicon', 'crossing the rubicon', 'dictator', 'dictator perpetuo',
      'dictator in perpetuity', 'senate', 'brutus', 'cleopatra', 'assassinated', 'betrayed by senators',
      'stabbed 23 times', 'conquered gaul', 'gallic wars', 'month of july', 'julian calendar'
    ],
    trivia: 'The month of July was named in his honor after he introduced the Julian calendar.',
    wikiTitle: 'Julius_Caesar'
  },
  {
    name: 'Napoleon Bonaparte',
    aliases: ['napoleon bonaparte', 'napoleon'],
    category: 'history',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'France',
    medium: 'real',
    era: 'historical',
    hair: 'brown',
    occupation: 'emperor',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['artillery', 'grande armee'],
    deathType: 'natural',
    conditions: [],
    tags: [
      'france', 'waterloo', 'battle of waterloo', 'general', 'emperor', 'emperor of the french',
      'crowned at notre-dame', 'corsica', 'conquest', 'tricorne', 'exiled to remote island',
      'exiled to saint helena', 'elba', 'napoleonic code', 'civil law'
    ],
    trivia: 'The belief that he was extremely short was British propaganda; at 5\'6", he was average height for a Frenchman of his era.',
    wikiTitle: 'Napoleon'
  },
  {
    name: 'Mahatma Gandhi',
    aliases: ['mahatma gandhi', 'gandhi', 'bapu'],
    category: 'history',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'India',
    medium: 'real',
    era: 'historical',
    hair: 'bald',
    occupation: 'activist',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['non-violence', 'satyagraha', 'hunger strike'],
    deathType: 'assassination',
    conditions: ['glasses', 'baldness'],
    tags: [
      'india', 'non-violence', 'nonviolent civil disobedience', 'ahimsa', 'satyagraha', 'salt march',
      'protest salt tax', 'independence', 'indian independence', 'peace', 'khadi', 'charkha',
      'glasses', 'assassinated', 'south africa civil rights'
    ],
    trivia: 'His philosophy of nonviolent civil disobedience inspired civil rights leaders worldwide, including Martin Luther King Jr.',
    wikiTitle: 'Mahatma_Gandhi'
  },
  {
    name: 'Abraham Lincoln',
    aliases: ['abraham lincoln', 'lincoln', 'honest abe'],
    category: 'history',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'historical',
    hair: 'black',
    occupation: 'president',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['speeches', 'union army'],
    deathType: 'assassination',
    conditions: ['tall', 'beard'],
    tags: [
      'civil war', 'american civil war', 'emancipation proclamation', 'abolish slavery', 'top hat',
      'stovepipe hat', 'gettysburg', 'gettysburg address', 'four score and seven years ago',
      'beard', 'chinstrap beard', 'president', 'us president', 'assassinated', 'john wilkes booth',
      'theatrical performance', 'fords theatre', 'ford’s theatre'
    ],
    trivia: 'Before his presidency, he was an elite wrestler who was enshrined in the National Wrestling Hall of Fame.',
    wikiTitle: 'Abraham_Lincoln'
  },

  // ==================== SPORTS LEGENDS ====================
  {
    name: 'Lionel Messi',
    aliases: ['lionel messi', 'messi', 'leo messi', 'la pulga'],
    category: 'sports',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Argentina',
    medium: 'real',
    era: 'modern',
    hair: 'brown',
    occupation: 'footballer',
    primarySport: 'football', // soccer
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['left foot dribble'],
    deathType: 'alive',
    conditions: ['growth hormone deficiency as child'],
    tags: [
      'football', 'soccer', 'barcelona', 'fc barcelona', 'world cup 2022', 'fifa world cup', 'world cup trophy',
      'national team argentina', 'ballon d or', 'eight ballon d or', 'ballon d’or', 'inter miami',
      'left foot', 'left-foot dribbling', 'goat', 'fifa', 'cafeteria paper napkin', 'paper napkin contract'
    ],
    trivia: 'His first official contract with FC Barcelona was signed on a paper napkin in a cafeteria.',
    wikiTitle: 'Lionel_Messi'
  },
  {
    name: 'Cristiano Ronaldo',
    aliases: ['cristiano ronaldo', 'ronaldo', 'cr7', 'cristiano'],
    category: 'sports',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Portugal',
    medium: 'real',
    era: 'modern',
    hair: 'dark',
    occupation: 'footballer',
    primarySport: 'football', // soccer
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['knuckleball free kick', 'jumping header'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'football', 'soccer', 'real madrid', 'manchester united', 'al nassr', 'siiiu', 'siuuu',
      'champions league', 'five champions league', 'goat', 'cr7', 'portugal', 'all-time international goalscorer',
      'five ballon d or', 'ballon d’or'
    ],
    trivia: 'He is the all-time leading international goalscorer in men\'s football history.',
    wikiTitle: 'Cristiano_Ronaldo'
  },
  {
    name: 'Michael Jordan',
    aliases: ['michael jordan', 'jordan', 'mj', 'air jordan'],
    category: 'sports',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'bald',
    occupation: 'basketball player',
    primarySport: 'basketball',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['fadeaway jump shot', 'dunks'],
    deathType: 'alive',
    conditions: ['baldness'],
    tags: [
      'nba', 'chicago bulls', 'jersey number 23', 'number 23', 'basketball', 'dunk', 'slam dunks',
      'free-throw line', 'sneakers', 'air jordan', 'nike', 'goat', 'rings', 'six championships',
      'six nba championships', 'finals mvp', 'baseball', 'birmingham barons', 'white sox'
    ],
    trivia: 'He won six NBA championships with the Chicago Bulls, named MVP in all six finals.',
    wikiTitle: 'Michael_Jordan'
  },
  {
    name: 'Usain Bolt',
    aliases: ['usain bolt', 'bolt', 'lightning bolt'],
    category: 'sports',
    fictional: false,
    gender: 'male',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'Jamaica',
    medium: 'real',
    era: 'modern',
    hair: 'black',
    occupation: 'sprinter',
    primarySport: 'sprinting',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['sprinting speed'],
    deathType: 'alive',
    conditions: ['scoliosis'],
    tags: [
      'olympics', 'fastest man', 'fastest human', '100m', '100 meters', '9.58 seconds', '200m', '200 meters',
      '19.19 seconds', 'world record', 'jamaica', 'lightning pose', 'lightning bolt victory pose',
      'gold medal', 'eight-time olympic gold', 'track and field', 'sprinting'
    ],
    trivia: 'He holds the world record for the 100 meters at an astonishing 9.58 seconds.',
    wikiTitle: 'Usain_Bolt'
  },

  // ==================== MUSIC LEGENDS ====================
  {
    name: 'Michael Jackson',
    aliases: ['michael jackson', 'mj', 'king of pop'],
    category: 'music',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'black',
    occupation: 'singer',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['vocal agility', 'dance moves'],
    deathType: 'assassination', // cardiac arrest from propofol
    conditions: ['vitiligo'],
    tags: [
      'king of pop', 'thriller', 'best-selling album', 'moonwalk', 'dance glide', 'single glove',
      'wearing a single glove', 'billie jean', 'beat it', 'smooth criminal', 'bad', 'pop music',
      'dancer', 'fedora', 'black fedora', 'white socks', 'jackson 5'
    ],
    trivia: 'His 1982 album Thriller remains the best-selling studio album of all time worldwide.',
    wikiTitle: 'Michael_Jackson'
  },
  {
    name: 'Taylor Swift',
    aliases: ['taylor swift', 'taylor'],
    category: 'music',
    fictional: false,
    gender: 'female',
    alive: true,
    human: true,
    superpowers: false,
    origin: 'USA',
    medium: 'real',
    era: 'modern',
    hair: 'blonde',
    occupation: 'singer',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['songwriting', 'guitar'],
    deathType: 'alive',
    conditions: [],
    tags: [
      'eras tour', 'pop music', 'country', 'grammy', 'swifties', 'guitar', 'songwriter',
      'four album of the year', 'album of the year four times', 'nashville', 'discography'
    ],
    trivia: 'She is the first artist ever to win the Grammy for Album of the Year four times.',
    wikiTitle: 'Taylor_Swift'
  },
  {
    name: 'Freddie Mercury',
    aliases: ['freddie mercury', 'farrokh bulsara'],
    category: 'music',
    fictional: false,
    gender: 'male',
    alive: false,
    human: true,
    superpowers: false,
    origin: 'United Kingdom',
    medium: 'real',
    era: 'historical',
    hair: 'black',
    occupation: 'singer',
    alterEgo: false,
    orphan: false,
    alignment: 'hero',
    weapons: ['four octave vocal range', 'piano'],
    deathType: 'cancer/illness', // AIDS complications
    conditions: ['mustache'],
    tags: [
      'queen', 'bohemian rhapsody', 'live aid', 'live aid in 1985', 'wembley stadium', 'mustache',
      'dark chevron mustache', 'rock star', 'vocal range', 'four-octave vocal range', 'piano',
      'farrokh bulsara', 'zanzibar', 'stone town', 'aids'
    ],
    trivia: 'His remarkable four-octave vocal range is considered one of the greatest phenomena in rock history.',
    wikiTitle: 'Freddie_Mercury'
  }
];
